# Generated by Django 5.1.1 on 2024-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0003_remove_menuitem_named_url_menuitem_slug_name_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug_name_url',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='Slug url name to menu item detail'),
        ),
    ]
