# Generated by Django 5.1.1 on 2024-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0004_alter_menuitem_slug_name_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug_name_url',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True, verbose_name='Slug url name to menu item detail'),
        ),
    ]
