# Generated by Django 5.1.1 on 2024-10-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0009_alter_menu_name_alter_menuitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='slug_name_url',
            new_name='named_url',
        ),
    ]
